version: '2'
services:
  consul:
    image: consul:1.6
    expose:
    - '8300'
    - '8500'
    - '8600'
    command: agent -server -bind 0.0.0.0 -client 0.0.0.0 -bootstrap-expect=1 -ui
  postgresql:
    image: postgres:11
    expose:
    - '5432'
    env_file:
    - ./envs/common.env
  redis:
    image: redis:5.0-alpine
    expose:
    - '6379'
  router-confd:
    image: wazoplatform/wazo-router-confd:latest
    depends_on:
      - consul
      - redis
      - postgresql
    ports:
    - 9600:9600
    env_file:
    - ./envs/common.env
    command: "wazo-router-confd \
        --host 0.0.0.0 --port 9600 \
        --advertise-host router-confd \
        --advertise-port 9600 \
        --consul-uri http://consul:8500 \
        --database-uri postgresql://wazo:wazo@postgresql:5432/wazo \
        --redis-uri redis://redis"
  rtpe:
    image: wazoplatform/wazo-rtpe:latest
    env_file:
    - ./envs/common.env
    - ./envs/rtpe.env
    environment:
      LISTEN_NG: 22222
      SUBSCRIBE_KEYSPACE: 2
  rtpe_secondary:
    image: wazoplatform/wazo-rtpe:latest
    env_file:
    - ./envs/common.env
    - ./envs/rtpe.env
    environment:
      LISTEN_NG: 22222
      SUBSCRIBE_KEYSPACE: 1
  sbc:
    image: 'wazoplatform/wazo-c4-sbc:latest'
    env_file:
    - ./envs/common.env
    - ./envs/sbc.env
    ports:
    - "5060:5060/udp"
    environment:
      LISTEN_ADVERTISE: sbc:5060
      ALIAS: sbc_secondary:5060
      DMQ_NOTIFICATION_ADDRESS: "sip:sbc_secondary:5062"
  sbc_secondary:
    image: 'wazoplatform/wazo-c4-sbc:latest'
    env_file:
    - ./envs/common.env
    - ./envs/sbc.env
    environment:
      LISTEN_ADVERTISE: sbc_secondary:5060
      ALIAS: sbc:5060
      DMQ_NOTIFICATION_ADDRESS: "sip:sbc:5062"
  router:
    image: 'wazoplatform/wazo-c4-router:latest'
    env_file:
    - ./envs/common.env
    - ./envs/router.env
    environment:
      LISTEN_ADVERTISE: router:5061
      ALIAS: router_secondary:5061
      DMQ_NOTIFICATION_ADDRESS: "sip:router_secondary:5062"
      DISPATCHER_WEIGHT: 10
  router_secondary:
    image: 'wazoplatform/wazo-c4-router:latest'
    env_file:
    - ./envs/common.env
    - ./envs/router.env
    environment:
      LISTEN_ADVERTISE: router_secondary:5061
      ALIAS: router:5061
      DMQ_NOTIFICATION_ADDRESS: "sip:router:5062"
      DISPATCHER_WEIGHT: 5
  carrier:
    image: 'wazoplatform/wazo-c4-carrier:latest'
    entrypoint: 'sipp -sf /scenarios/uas.xml'
  wazo-tester:
    image: 'wazoplatform/wazo-tester:latest'
    depends_on:
      - router-confd
    environment:
      API_ENDPOINT: http://router-confd:9600
      TARGET: sbc:5060
    volumes:
    - "./tests/:/tests/"
    command: sh -c "while true; do sleep 30; done;"
